Feature/erc165 get supported interfaces #2429
OpenZeppelin/openzeppelin-contracts pull request #2469
Opened 2021-01-12 16:32 UTC by conspyrosy

New feature #2429 

See the issue, explained there.

Tests work. Linter giving me line errors in windows

2021-01-13 10:35 UTC, Amxx requested changes

2021-01-13 10:35 UTC, Amxx commented on contracts/introspection/ERC165Checker.sol
> +            if (!_supportsERC165Interface(account, interfaceIds[i])) {
I this doing
```
for (uint256 i = 0; i < interfaceIds.length; i++) {
    interfaceIdsSupported[i] = _supportsERC165Interface(account, interfaceIds[i]);
}
```
would be both clearer and possibly more gas efficiant

2021-01-13 10:35 UTC, Amxx commented on test/introspection/ERC165Checker.test.js
> +    it('does not support mock interface via getSupportedInterfaces', async function () {
Please don't remove the existing test and add the new one in a separate `it` just like you did for the other contexts

2021-01-13 10:45 UTC, Amxx commented
Not that by default, newly allocated arrays should contain 0 (@frangio can you confirme this?)

If so the getSupportedInterface can be shorten to:
```
function getSupportedInterfaces(address account, bytes4[] memory interfaceIds) internal view returns (bool[] memory) {
    // an array of booleans corresponding to interfaceIds and whether they're supported or not
    bool[] memory interfaceIdsSupported = new bool[](interfaceIds.length);
    
    // query support of ERC165 itself
    if (supportsERC165(account)) {
        // query support of each interface in interfaceIds
        for (uint256 i = 0; i < interfaceIds.length; ++i) {
            interfaceIdsSupported[i] = _supportsERC165Interface(account, interfaceIds[i]);
        }
    }
    
    return interfaceIdsSupported;
}
```

2021-01-14 00:28 UTC, frangio commented
Thanks @conspyrosy!

> I do believe that, by default, newly allocated arrays should contain 0 (@frangio can you confirme this?), which in boolean terms means false.

I'm pretty sure this is the case but I couldn't find it in the documentation for Solidity. I've asked the team to confirm.

2021-01-14 19:14 UTC, frangio commented
The reply from the Solidity team was:

>at the Solidity level, all newly allocated data structures are guaranteed to be initialized properly. At the assembly level, you cannot rely on 0x40 pointing to zeroed out memory

In summary, yes we can just initialize a new array.

2021-01-19 18:37 UTC, conspyrosy commented
I've only just got round to checking on this, looks like some changes have been made which look good 👍 Let me know if this needs anything from me.

2021-01-19 18:40 UTC, frangio commented
Hi @conspyrosy, no problem. Sorry that we jumped in, we want to ship this in the next release. :slightly_smiling_face:

2021-01-19 18:40 UTC, frangio approved these changes

2021-01-19 20:55 UTC, merged