Update and rename ReentrancyGuard.sol to MultiLevelReentrancyGuard.sol
OpenZeppelin/openzeppelin-contracts pull request #2767
Opened 2021-07-14 07:40 UTC by sudiptab2100

There might be multiple functions that needs to be `nonReentrant` for calls to themselves only, but using one modifier for every nonReentrant functions can pause the working of other functions when one is working. 
To solve the problem, this solution is proposed a multi level Reentrancy Guard. In this implementation, `nonReentrant` modifiers will have a parameter called `level`. This way non reentrant functions with different level can be executed concurrently & non reentrant functions that should not be working concurrently can be put in same level.

Fixes #???? 

#### PR Checklist

- [ ] Tests
- [ ] Documentation
- [ ] Changelog entry

2021-07-14 07:45 UTC, Thajuiceman69 approved these changes

2021-07-14 11:48 UTC, Amxx commented
Hello @sudiptab2100, and thank you for the proposal.

In the future, please raise an issue before proposing a PR. It is always better to discuss the feature before puting time into the code.

In its current form, your proposal has 2 big issues:

- It breaks backward compatibility with contract that expect te modifier to not have any argument.
- Using values 1 and 2 instead of 1 and 2 is very bad for gas usage. we want te state change to be as cheap as possible, and it is cheaper to update dirty storage (2 x 5k gas) then it is to set it from clean state (21k gas) and then cleaning with a refund.

I'd love to know more about the usecase. In any case, I would keep the old modifier, and I would make sure the gas usage are optimized

2021-07-14 11:50 UTC, Amxx requested changes
- Keep original modifier in the code (new features can be in a different modifier)
- Keep `uint256 private constant _NOT_ENTERED = 1;` and `uint256 private constant _ENTERED = 2;` for gas efficiency

2021-07-15 02:51 UTC, Thajuiceman69 commented
Thanks

2021-07-15 11:50 UTC, Amxx commented
Also, keep in mind that we want to keep storage compatibility in case user want to upgrade their contract.
Here, actual storage content is not really important, but we would still want to keep the `uint256 status` slot to avoid the upgrade plugins detecting what appears like an inconsistency

2021-07-16 15:10 UTC, frangio commented
@Thajuiceman69 Can you share an example use case to motivate this feature so we can decide if we want to include it?

2021-07-17 05:51 UTC, closed without merging