fix: make upgradeTo and upgradeToAndCall functions public (#3923)
OpenZeppelin/openzeppelin-contracts pull request #3959
Opened 2023-01-16 16:15 UTC by m-waqas88

Fixes Make upgradeTo functions public #3923 

Two functions upgradeTo and upgradeToAndCall were having visibility specifiers as `external` and `virtual`, due to this reason derived contract was not able to invoke the function using `super` keyword. I just replaced `external` with `public` so that it can be invoked as well as overridden as expected.

#### PR Checklist

- [ ] Tests
- [ ] Documentation
- [ ] Changelog entry

2023-01-18 18:21 UTC, JulissaDantes requested changes
Please check the other contracts using the `UUPSUpgradeable` contract. All the check must pass, and right now the library its not compiling.

2023-01-23 09:56 UTC, Amxx requested changes

2023-01-23 09:56 UTC, Amxx commented on .changeset/five-ducks-develop.md
> +---
This is not a valid changeset

2023-01-25 11:59 UTC, m-waqas88 commented on .changeset/five-ducks-develop.md
> +---
@JulissaDantes and @frangio 

What does line#2 means?

In line#5, just mentioned UUPSUpgradeable.sol whereas I also made changes to UUPSLegacy.sol and UUPSUpgradeableMock.sol

2023-01-25 13:19 UTC, Amxx commented on .changeset/five-ducks-develop.md
> +---
`UUPSLegacy.sol` and `UUPSUpgradeableMock.sol` are mocks. We don't document changes to the mocks.

2023-01-25 18:56 UTC, JulissaDantes commented on .changeset/five-ducks-develop.md
> +---
Remember to remove the changes to mocks in the changeset.

2023-01-25 19:46 UTC, frangio approved these changes
Thanks.

2023-01-25 19:46 UTC, merged