Remove unused named return variables.
OpenZeppelin/openzeppelin-contracts pull request #4573
Opened 2023-09-04 14:48 UTC by Amxx

Fixes LIB-1033

For consistency with the rest of the codebase, removing unused named variables from the methods' signatures

2023-09-04 17:05 UTC, frangio approved these changes

2023-09-04 17:07 UTC, frangio requested changes

2023-09-04 17:07 UTC, frangio commented on contracts/access/extensions/AccessControlDefaultAdminRules.sol
>          schedule = _pendingDelaySchedule;
```suggestion
        uint48 schedule = _pendingDelaySchedule;
```

2023-09-04 20:23 UTC, frangio commented
We are probably using the named return values in tests.

2023-09-05 08:28 UTC, Amxx commented
> We are probably using the named return values in tests.

Yes, we do ```const { newDelay, schedule } = await this.accessControl.pendingDefaultAdminDelay();```

2023-09-05 22:14 UTC, frangio approved these changes
I had added a new guideline:
> Functions with multiple return values should use named return values for clarity, even if the function uses an explicit `return` statement.

But reverted it because I don't think we should add the guideline without reviewing the rest of the codebase.

This is our intention though.

2023-09-06 09:35 UTC, merged